version: '3.8'
services:
  postgres-beautique:
    image: postgres
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    volumes:
      - './../db-beautique:/var/lib/postgresql/data'
      - './init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql'
    ports:
      - '3334:5432'
    networks:
      - beautique-network
  rabbitmq-beautique:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq-beautique
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5677:5672'
      - '15673:15672'
    volumes:
      - './../rabbitmq-beautique/rabbitmq-data:/var/lib/rabbitmq'
      - './../rabbitmq-beautique/rabbitmq-log:/var/log/rabbitmq'
    networks:
      - beautique-network
  mongodb-beautique:
    image: 'mongo:latest'
    hostname: mongodb-beautique
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - './../db-mongodb:/data/db'
      - './mongo-init.sh:/docker-entrypoint-initidb.d/mongo-init.sh'
    ports:
      - '37017:27017'
    networks:
      - beautique-network
networks:
  beautique-network:
    driver: bridge